import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

type Opportunity = {
  id: string;
  provider: string;
  title: string;
  subcategories: string[];
  url: string;
  description: string;
  eligibility: string;
  value: string;
  regions?: string[];
};

const communityMicrogrants: Opportunity[] = [
  ['awesome-foundation-grants','The Awesome Foundation','Awesome Foundation Grants','https://www.awesomefoundation.org/en','Local chapters award small grants for community projects and ideas.','Applicants propose a project to a participating local chapter and follow that chapter\'s criteria.','Chapter-funded microgrant for a selected project'],
  ['pollination-project-daily-grant','The Pollination Project','Daily Grant Program','https://thepollinationproject.org/apply/','Seed funding supports early-stage social-change projects led by individuals and small groups.','Individuals and informal groups with an early-stage social-change idea may apply under the current guidelines.','Seed grant for a selected social-change project'],
  ['ysa-youth-service-zone-grants','Youth Service America','Youth Service Grants','https://ysa.org/grants/','Youth Service America publishes grant opportunities for youth-led service and community projects.','Young people, educators, and organizations must meet the requirements of the current grant call.','Small grant for an eligible youth-led service project'],
  ['wikimedia-rapid-fund','Wikimedia Foundation','Wikimedia Rapid Fund','https://meta.wikimedia.org/wiki/Grants:Project/Rapid','Rapid Fund supports short-term, low-cost projects that benefit Wikimedia communities.','Individuals, groups, and organizations must propose eligible Wikimedia movement work in a supported region.','Rapid project funding under the current regional limits'],
  ['global-greengrants-fund','Global Greengrants Fund','Grassroots Environmental Grants','https://www.greengrants.org/what-we-do/grantmaking/','Small grants support grassroots environmental justice organizations and movements around the world.','Grassroots groups are identified through the fund\'s regional adviser networks rather than an open global application.','Flexible small grant for selected grassroots environmental work'],
  ['global-changemakers-community-action-grants','Global Changemakers','Community Action Grants','https://www.global-changemakers.net/grants','Grants support youth-led projects addressing challenges in their communities.','Young changemakers must satisfy the current program, training, age, and project requirements.','Project grant and support for selected youth-led action'],
  ['her-suite-spot-her-rise-microgrant','Her Suite Spot','HerRise MicroGrant','https://www.hersuitespot.com/herrise','Monthly microgrants support women of color building small businesses in the United States.','Applicants must meet the program\'s current ownership, location, and business-stage requirements.','Monthly microgrant for a selected business owner'],
  ['nase-growth-grants','National Association for the Self-Employed','NASE Growth Grants','https://www.nase.org/become-a-member/member-benefits/business-resources/growth-grants','Growth Grants provide small awards that eligible NASE members can use for business needs.','Applicants must be eligible NASE members and follow the current application and waiting-period rules.','Small-business grant under the current program limit'],
  ['freed-fellowship-grant','The Freed Fellowship','Freed Fellowship Grant','https://www.freedfellowship.com/grant','Monthly grants and feedback support selected small-business owners.','Small-business owners must submit the current application and meet the organizer\'s terms.','Monthly business microgrant and feedback'],
  ['galaxy-grant','Hidden Star','Galaxy Grant','https://galaxyofstars.org/','Galaxy of Stars offers grant rounds and business support for women and minority entrepreneurs.','Applicants must meet the current grant round\'s ownership, business, and application requirements.','Small-business grant under the current Galaxy Grant round'],
].map(([id,provider,title,url,description,eligibility,value]) => ({id,provider,title,url,description,eligibility,value,subcategories:['grants','microgrants','community-funds']}));

const researchFellowships: Opportunity[] = [
  ['nsf-graduate-research-fellowship','U.S. National Science Foundation','NSF Graduate Research Fellowship Program','https://www.nsf.gov/funding/opportunities/grfp-nsf-graduate-research-fellowship-program','The program provides multi-year support for eligible graduate students pursuing research-based degrees in NSF-supported fields.','Applicants must satisfy the current citizenship, education-stage, degree, and field requirements.','Multi-year stipend and education allowance'],
  ['marie-sklodowska-curie-postdoctoral-fellowships','European Commission','Marie Sklodowska-Curie Postdoctoral Fellowships','https://marie-sklodowska-curie-actions.ec.europa.eu/actions/postdoctoral-fellowships','Postdoctoral Fellowships fund researcher mobility, training, and research projects in Europe and beyond.','Researchers and host organizations must meet the call\'s experience, mobility, and proposal requirements.','Salary, mobility, research, training, and institutional support'],
  ['fulbright-us-scholar-program','Fulbright Scholar Program','Fulbright U.S. Scholar Program','https://fulbrightscholars.org/us-scholar-awards','Awards support eligible U.S. scholars and professionals teaching or conducting research abroad.','Applicants must meet the citizenship, experience, discipline, destination, and award-specific criteria.','Funded international teaching or research award'],
  ['hfsp-postdoctoral-fellowships','Human Frontier Science Program','HFSP Postdoctoral Fellowships','https://www.hfsp.org/funding/hfsp-funding/postdoctoral-fellowships','Fellowships support early-career scientists undertaking interdisciplinary life-science research in another country.','Applicants must satisfy the doctorate, publication, mobility, host-lab, and research-scope rules.','Multi-year fellowship support for international postdoctoral research'],
  ['hertz-fellowship','Fannie and John Hertz Foundation','Hertz Fellowship','https://www.hertzfoundation.org/the-fellowship/','The fellowship funds doctoral study for selected U.S. students in applied physical and biological sciences, mathematics, and engineering.','Applicants must meet current citizenship or residency, study-stage, and field requirements.','Graduate tuition and personal stipend'],
  ['aauw-american-fellowships','AAUW','American Fellowships','https://www.aauw.org/resources/programs/fellowships-grants/current-opportunities/american/','American Fellowships support women completing dissertations, postdoctoral research, or research for publication.','Applicants must meet the program\'s gender, residency, degree, institution, and project-stage criteria.','Fellowship funding for eligible academic work'],
  ['schmidt-science-fellows','Schmidt Science Fellows','Schmidt Science Fellows Program','https://schmidtsciencefellows.org/program/','A funded postdoctoral fellowship supports scientists pivoting into a new discipline to pursue interdisciplinary research.','Candidates must be nominated by an eligible institution and meet the current PhD and research criteria.','Stipend, scientific placement, mentoring, and cohort programming'],
  ['canada-postdoctoral-research-award','Government of Canada','Canada Postdoctoral Research Award','https://nserc-crsng.canada.ca/en/funding-opportunity/canada-postdoctoral-research-award-program','The harmonized federal award funds postdoctoral research across health, natural sciences, engineering, social sciences, and humanities.','Applicants must meet the current degree timing, position, agency, research, and application requirements.','Two-year postdoctoral research award'],
  ['wellcome-early-career-awards','Wellcome','Early-Career Awards','https://wellcome.org/research-funding/schemes/early-career-awards','Awards fund early-career researchers ready to develop an independent research identity in eligible health-related fields.','Applicants and administering organizations must meet Wellcome\'s current career-stage, location, and research-remit rules.','Salary and research expenses for an eligible project'],
  ['embl-ebi-arise-fellowship','EMBL-EBI','ARISE Fellowship Programme','https://www.embl.org/about/info/arise/','ARISE fellowships train researchers and engineers developing research infrastructures for the life sciences.','Applicants must satisfy the call\'s degree, experience, mobility, and project requirements.','Funded fellowship, training, and research-infrastructure placement'],
].map(([id,provider,title,url,description,eligibility,value]) => ({id,provider,title,url,description,eligibility,value,subcategories:['grants','funded-fellowships','research-funding']}));

const prizePrograms: Opportunity[] = [
  ['xprize-competitions','XPRIZE Foundation','XPRIZE Competitions','https://www.xprize.org/prizes','XPRIZE runs large incentive competitions that award teams for achieving defined technical or social-impact goals.','Teams must register for a current prize and meet its rules, milestones, and judging requirements.','Prize purse varies by active competition'],
  ['earthshot-prize','The Earthshot Prize','The Earthshot Prize','https://earthshotprize.org/the-prize/awards/','The annual prize recognizes and funds scalable solutions to major environmental challenges.','Solutions generally enter through official nominators and must satisfy the current selection criteria.','Major monetary award and scale-up support for winners'],
  ['mit-solve-global-challenges','MIT Solve','Global Challenges','https://solve.mit.edu/challenges','Open innovation challenges select and support technology-based social-impact solutions.','Teams must apply to an active challenge and meet its solution-stage and impact requirements.','Prize funding, partnerships, and a support network'],
  ['hult-prize','Hult Prize Foundation','Hult Prize','https://www.hultprize.org/','A global student competition supports ventures addressing an annual social-impact challenge.','Student teams must meet current participation, team, pathway, and venture requirements.','Venture prize and accelerator support'],
  ['james-dyson-award','James Dyson Foundation','James Dyson Award','https://www.jamesdysonaward.org/','The international design award recognizes student and recent-graduate inventions that solve real problems.','Entrants must meet current country, education, project, and originality requirements.','National and international monetary awards'],
  ['loreal-unesco-for-women-in-science','L\'Oreal Foundation and UNESCO','For Women in Science International Awards','https://www.unesco.org/en/prizes/women-science','The program recognizes and supports women scientists through international awards and regional fellowships.','Candidates must meet the applicable scientific field, career, geography, and nomination criteria.','Research award or fellowship funding'],
  ['longitude-prize','Challenge Works','Longitude Prize','https://longitudeprize.org/','Longitude Prize competitions reward teams developing solutions to major global challenges.','Teams must enter an active prize and comply with its technical and judging rules.','Challenge-specific development awards and winner prize'],
  ['zayed-sustainability-prize','Zayed Sustainability Prize','Zayed Sustainability Prize','https://zayedsustainabilityprize.com/','The prize recognizes organizations and schools delivering sustainable solutions across several impact categories.','Applicants must meet the category-specific organization, impact, innovation, and submission criteria.','Monetary prize and global recognition'],
  ['global-student-prize','Chegg.org and Varkey Foundation','Global Student Prize','https://globalteacherprize.org/pages/eligibility-criteria-1','The annual award recognizes an exceptional student making a real impact on learning and society.','Applicants or nominees must meet the current age, enrollment, and impact criteria.','Global monetary prize for the selected student'],
  ['falling-walls-lab','Falling Walls Foundation','Falling Walls Lab','https://falling-walls.com/lab','Emerging researchers and innovators pitch breakthrough ideas through local labs and a global finale.','Applicants must meet current academic or professional stage rules and apply through an available lab.','Pitch platform, global final, recognition, and winner opportunities'],
].map(([id,provider,title,url,description,eligibility,value]) => ({id,provider,title,url,description,eligibility,value,subcategories:['prizes']}));

const creatorFunds: Opportunity[] = [
  ['creative-capital-award','Creative Capital','Creative Capital Award','https://creative-capital.org/creative-capital-award/','The award provides project funding and professional development to selected artists creating original work.','Artists must meet the current discipline, project, age, residency, and application requirements.','Unrestricted project funding and artist services'],
  ['sundance-documentary-fund','Sundance Institute','Documentary Fund','https://www.sundance.org/programs/documentary-film/','The Documentary Fund supports nonfiction filmmakers through development, production, and post-production grants.','Independent nonfiction projects must meet the current application stage, creative, and eligibility criteria.','Documentary project grant and creative support'],
  ['catapult-film-fund','Catapult Film Fund','Catapult Development Grant','https://catapultfilmfund.org/how-to-apply/','Development grants support documentary filmmakers creating a strong sample for an early-stage film.','Filmmakers must meet the fund\'s documentary, project-stage, budget, and application requirements.','Development grant for a selected documentary'],
  ['berkeley-documentary-grant','Berkeley Film Foundation','Documentary Grant Program','https://berkeleyfilmfoundation.org/documentary-grant-program','The annual program provides production grants to documentary filmmakers based in the San Francisco Bay Area.','Primary creators must meet the current residence, project-stage, documentary, and application requirements.','Documentary production grant for a selected local filmmaker'],
  ['pulitzer-center-reporting-grants','Pulitzer Center','Reporting Grants','https://pulitzercenter.org/opportunities/reporting-grants-fellowships','Reporting grants support journalists pursuing consequential stories across the Pulitzer Center\'s focus areas.','Journalists and newsrooms must apply to a current opportunity and meet its editorial and geographic criteria.','Reporting expenses and editorial support'],
  ['national-geographic-society-grants','National Geographic Society','Grants and Investments','https://www.nationalgeographic.org/society/grants-and-investments/','Funding supports selected explorers working in science, conservation, education, storytelling, and technology.','Applicants must apply to a current funding opportunity and meet its project and expertise requirements.','Project grant and National Geographic Explorer community support'],
  ['journalismfund-europe-grants','Journalismfund Europe','Journalism Grants','https://www.journalismfund.eu/grants','Grant programs fund cross-border, local, environmental, and other public-interest journalism in Europe.','Journalists and teams must meet the chosen call\'s geography, collaboration, publication, and budget rules.','Reporting grant for an eligible journalism project'],
  ['black-public-media-360-incubator','Black Public Media','360 Incubator+','https://blackpublicmedia.org/360-incubator/','The incubator supports Black filmmakers and creative technologists developing broadcast and digital projects.','Creators must satisfy the current call\'s identity, project-stage, medium, and participation requirements.','Development support, mentorship, pitch opportunity, and potential funding'],
  ['center-for-cultural-innovation-grants','Center for Cultural Innovation','Grants for Artists','https://cciarts.org/grants-programs/','CCI administers grant programs for artists and creative workers, with eligibility varying by current call.','Artists must apply to an open program and meet its discipline, location, and project requirements.','Artist grant under an available program'],
  ['nea-creative-writing-fellowships','National Endowment for the Arts','Creative Writing Fellowships','https://www.arts.gov/grants/creative-writing-fellowships','Fellowships provide monetary awards to published creative writers, alternating between prose and poetry cycles.','Writers must meet the current publication and U.S. eligibility requirements.','Creative-writing fellowship award'],
].map(([id,provider,title,url,description,eligibility,value]) => ({id,provider,title,url,description,eligibility,value,subcategories:['grants','creator-funds']}));

const openSourceSponsorships: Opportunity[] = [
  ['github-sponsors','GitHub','GitHub Sponsors','https://github.com/sponsors','GitHub Sponsors lets eligible open-source contributors receive recurring or one-time financial support.','Contributors must live in a supported region and meet GitHub\'s account, tax, profile, and conduct requirements.','Direct community sponsorship with GitHub charging no platform fee for personal sponsorships'],
  ['open-collective-open-source-collective','Open Source Collective','Open Source Collective Fiscal Hosting','https://oscollective.org/','Open Source Collective provides fiscal hosting so qualifying open-source projects can receive and manage community funding.','Open-source projects must apply and meet the collective\'s public-benefit, governance, licensing, and reporting requirements.','Fiscal hosting and transparent community funding'],
  ['polar-open-source-funding','Polar','Polar for Open Source','https://polar.sh/','Polar provides tools for open-source maintainers to fund work through subscriptions, products, and issue-based rewards.','Maintainers need an eligible open-source project and must satisfy Polar\'s account, payment, and platform terms.','Community funding and paid issue or product infrastructure'],
  ['liberapay','Liberapay','Liberapay','https://liberapay.com/','Liberapay enables recurring donations to creators and open-source contributors without taking a platform percentage.','Recipients need an eligible account and payment setup in a supported country.','Recurring community donations'],
  ['tidelift-lifter-program','Tidelift','Tidelift Lifter Program','https://tidelift.com/subscription/managed-open-source','Tidelift contracts with participating maintainers to perform package maintenance and supply-chain assurance work.','Maintainers of packages in customer dependency catalogs may be invited or apply under current program requirements.','Paid maintainer work through the Tidelift subscription'],
  ['thanks-dev','thanks.dev','thanks.dev','https://thanks.dev/','thanks.dev distributes sponsor funding across the open-source dependencies used by participating organizations and individuals.','Open-source maintainers need supported repositories and payout details under the platform\'s current rules.','Dependency-based recurring sponsorship'],
  ['issuehunt','IssueHunt','IssueHunt','https://issuehunt.io/','IssueHunt connects funded issues and open-source contributors, allowing work on eligible issues to receive bounties.','Projects and contributors must use supported repositories and comply with current bounty and payment rules.','Issue bounty or project sponsorship'],
  ['drips-network','Drips','Drips','https://www.drips.network/solutions/ecosystem-funding','Drips provides open-source funding infrastructure that lets projects receive and share recurring support through dependency networks.','Projects and supporters must use a supported account and comply with the protocol and platform requirements.','Recurring and dependency-aware open-source funding'],
  ['kilo-open-source-sponsorship','Kilo Code','Open Source Sponsorship Program','https://kilo.ai/oss','The program sponsors eligible open-source projects with access to Kilo Code resources and program benefits.','Projects must meet current open-source licensing, activity, usage, and application requirements.','Open-source project sponsorship and product resources'],
  ['opencollective-funding-platform','Open Collective','Open Collective','https://opencollective.com/','Open Collective helps transparent groups and open-source projects collect and manage money through a fiscal host or independent entity.','Collectives must select an available fiscal setup and comply with host, payment, and transparency requirements.','Transparent donations, sponsorships, budgets, and expense management'],
].map(([id,provider,title,url,description,eligibility,value]) => ({id,provider,title,url,description,eligibility,value,subcategories:['community-funds','open-source-sponsorships']}));

const rows = [...communityMicrogrants, ...researchFellowships, ...prizePrograms, ...creatorFunds, ...openSourceSponsorships];
const outputDirectory = resolve(process.cwd(), 'opportunities');
await mkdir(outputDirectory, { recursive: true });

for (const row of rows) {
  const opportunity = {
    id: row.id,
    provider: row.provider,
    title: row.title,
    category: 'funding',
    subcategories: row.subcategories,
    tags: ['funding'],
    description: row.description,
    eligibility: row.eligibility,
    value: row.value,
    sourceUrl: row.url,
    officialUrl: row.url,
    status: 'limited',
    submissionType: 'maintainer',
    sponsor: false,
    reviewDate: '2026-07-18',
    regions: row.regions ?? ['Global'],
  };
  await writeFile(resolve(outputDirectory, `${row.id}.json`), `${JSON.stringify(opportunity, null, 2)}\n`);
}

console.log(`Wrote ${rows.length} curated funding opportunities.`);
